### ISSUE TITLE
[ry] localでの環境開発及び動作確認

### ISSUE THREAD

**Issue by ryojsb** [cloudnativedaysjp/dreamkast-kanban#29]

**Comment by ryojsb** [comment]
- dreamkast

```
% docker-compose up -d                                        
WARNING: The SENTRY_DSN variable is not set. Defaulting to a blank string.
WARNING: The S3_BUCKET variable is not set. Defaulting to a blank string.
WARNING: The AUTH0_CLIENT_ID variable is not set. Defaulting to a blank string.
WARNING: The AUTH0_CLIENT_SECRET variable is not set. Defaulting to a blank string.
WARNING: The AUTH0_DOMAIN variable is not set. Defaulting to a blank string.
WARNING: The RAILS_MASTER_KEY variable is not set. Defaulting to a blank string.
Docker Compose is now in the Docker CLI, try `docker compose up`

Creating network "dreamkast_default" with the default driver
Creating dreamkast_nginx_1 ... done
Creating dreamkast_ui_1    ... done
Creating dreamkast_db_1    ... done
Creating dreamkast_redis_1 ... done
Creating dreamkast_app_1   ... done

% docker ps
CONTAINER ID   IMAGE                                                                 COMMAND                  CREATED          STATUS          PORTS                               NAMES
f5e583394de8   mysql:8                                                               "docker-entrypoint.s…"   22 seconds ago   Up 15 seconds   0.0.0.0:3306->3306/tcp, 33060/tcp   dreamkast_db_1
c2562dbc579a   nginx                                                                 "/docker-entrypoint.…"   22 seconds ago   Up 13 seconds   0.0.0.0:8080->80/tcp                dreamkast_nginx_1
793318a104d7   redis:6                                                               "docker-entrypoint.s…"   22 seconds ago   Up 11 seconds   0.0.0.0:6379->6379/tcp              dreamkast_redis_1
e04b35248ef4   607167088920.dkr.ecr.ap-northeast-1.amazonaws.com/dreamkast-ui:main   "docker-entrypoint.s…"   22 seconds ago   Up 17 seconds   0.0.0.0:3001->3001/tcp              dreamkast_ui_1
```

`http://localhost:3001` へのアクセス後、`404` が返ってくる。

この後、https://github.com/cloudnativedaysjp/dreamkast を見ながら対応予定

- dreamkast-ui

```
% docker-compose up -d            
WARNING: The SENTRY_DSN variable is not set. Defaulting to a blank string.
WARNING: The S3_BUCKET variable is not set. Defaulting to a blank string.
WARNING: The AUTH0_CLIENT_ID variable is not set. Defaulting to a blank string.
WARNING: The AUTH0_CLIENT_SECRET variable is not set. Defaulting to a blank string.
WARNING: The AUTH0_DOMAIN variable is not set. Defaulting to a blank string.
WARNING: The RAILS_MASTER_KEY variable is not set. Defaulting to a blank string.
Docker Compose is now in the Docker CLI, try `docker compose up`

Creating network "dreamkast-ui_default" with the default driver
Creating dreamkast-ui_redis_1 ... done
Creating dreamkast-ui_nginx_1 ... done
Creating dreamkast-ui_db_1    ... done
Creating dreamkast-ui_app_1   ... done
% docker ps
CONTAINER ID   IMAGE     COMMAND                  CREATED          STATUS          PORTS                               NAMES
59f329a3ba21   nginx     "/docker-entrypoint.…"   15 seconds ago   Up 7 seconds    0.0.0.0:8080->80/tcp                dreamkast-ui_nginx_1
02e6e4792b4a   mysql:8   "docker-entrypoint.s…"   15 seconds ago   Up 9 seconds    0.0.0.0:3306->3306/tcp, 33060/tcp   dreamkast-ui_db_1
bbbca33800f4   redis:6   "docker-entrypoint.s…"   15 seconds ago   Up 11 seconds   0.0.0.0:6379->6379/tcp              dreamkast-ui_redis_1
```

`http://localhost:8080/cndo2021/ui` アクセス後、`502` が返ってくる。

**Comment by ryojsb** [comment]
```
% bundle install                                                                                                      
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
Fetching gem metadata from https://rubygems.org/............
Using rake 13.0.1
Using concurrent-ruby 1.1.6
Using i18n 1.8.3
Using minitest 5.14.1
Using thread_safe 0.3.6
Using tzinfo 1.2.7
Using zeitwerk 2.3.0
Using activesupport 6.0.3.1
Using builder 3.2.4
Using erubi 1.9.0
Using mini_portile2 2.5.0
Using racc 1.5.2
Using nokogiri 1.11.1 (x86_64-darwin)
Using rails-dom-testing 2.0.3
Using crass 1.0.6
Using loofah 2.5.0
Using rails-html-sanitizer 1.3.0
Using actionview 6.0.3.1
Using rack 2.2.3
Using rack-test 1.1.0
Using actionpack 6.0.3.1
Using nio4r 2.5.2
Using websocket-extensions 0.1.5
Using websocket-driver 0.7.2
Using actioncable 6.0.3.1
Using globalid 0.4.2
Using activejob 6.0.3.1
Using activemodel 6.0.3.1
Using activerecord 6.0.3.1
Using mimemagic 0.3.9
Using marcel 0.3.3
Using activestorage 6.0.3.1
Using mini_mime 1.0.2
Using mail 2.7.1
Using actionmailbox 6.0.3.1
Using actionmailer 6.0.3.1
Using actiontext 6.0.3.1
Using activerecord-nulldb-adapter 0.7.0
Using public_suffix 4.0.6
Using addressable 2.7.0
Using awesome_nested_set 3.3.1
Using aws-eventstream 1.1.0
Using aws-partitions 1.423.0
Using aws-sigv4 1.2.2
Using jmespath 1.4.0
Using aws-sdk-core 3.112.0
Using aws-sdk-dynamodb 1.59.0
Using aws-record 2.5.0
Using aws-sdk-kms 1.42.0
Using aws-sdk-ses 1.37.0
Using aws-sdk-sqs 1.36.0
Using aws-sessionstore-dynamodb 2.0.1
Using method_source 1.0.0
Using thor 1.0.1
Using railties 6.0.3.1
Using aws-sdk-rails 3.6.0
Using aws-sdk-s3 1.88.0
Using bindex 0.8.1
Using msgpack 1.3.3
Using bootsnap 1.4.6
Using uniform_notifier 1.13.0
Using bullet 6.1.0
Using bundler 2.1.4
Using byebug 11.1.3
Using regexp_parser 1.7.1
Using xpath 3.2.0
Using capybara 3.32.2
Using childprocess 3.0.0
Using coderay 1.1.3
Using json_schema 0.20.9
Using openapi_parser 0.12.1
Using committee 4.3.0
Using committee-rails 0.5.1
Using content_disposition 1.0.0
Using debase-ruby_core_source 0.10.9
Using debase 0.2.4.1
Using diff-lcs 1.4.2
Using down 5.2.0
Using factory_bot 6.1.0
Using factory_bot_rails 6.1.0
Using multipart-post 2.1.1
Using ruby2_keywords 0.0.2
Using faraday 1.1.0
Using ffi 1.13.1
Using hashie 4.1.0
Using jbuilder 2.10.0
Using jwt 2.2.2
Using rb-fsevent 0.10.4
Using rb-inotify 0.10.1
Using listen 3.2.1
Using multi_json 1.15.0
Using multi_xml 0.6.0
Fetching mysql2 0.5.3
Installing mysql2 0.5.3 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/ry/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/mysql2-0.5.3/ext/mysql2
/Users/ry/.rbenv/versions/2.7.2/bin/ruby -I /Users/ry/.rbenv/versions/2.7.2/lib/ruby/2.7.0 -r ./siteconf20210516-99736-1gyt7bf.rb extconf.rb
--with-ldflags\=-L/usr/local/opt/openssl@1.1/lib --with-cppflags\=-I/usr/local/opt/openssl@1.1/include
checking for rb_absint_size()... yes
checking for rb_absint_singlebit_p()... yes
checking for rb_wait_for_single_fd()... yes
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/Users/ry/.rbenv/versions/2.7.2/bin/$(RUBY_BASE_NAME)
        --with-mysql-dir
        --without-mysql-dir
        --with-mysql-include
        --without-mysql-include=${mysql-dir}/include
        --with-mysql-lib
        --without-mysql-lib=${mysql-dir}/lib
        --with-mysql-config
        --without-mysql-config
        --with-mysqlclient-dir
        --without-mysqlclient-dir
        --with-mysqlclient-include
        --without-mysqlclient-include=${mysqlclient-dir}/include
        --with-mysqlclient-lib
        --without-mysqlclient-lib=${mysqlclient-dir}/lib
        --with-mysqlclientlib
        --without-mysqlclientlib
/Users/ry/.rbenv/versions/2.7.2/lib/ruby/2.7.0/mkmf.rb:1050:in `block in find_library': undefined method `split' for nil:NilClass (NoMethodError)
        from /Users/ry/.rbenv/versions/2.7.2/lib/ruby/2.7.0/mkmf.rb:1050:in `collect'
        from /Users/ry/.rbenv/versions/2.7.2/lib/ruby/2.7.0/mkmf.rb:1050:in `find_library'
        from extconf.rb:87:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/ry/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/extensions/x86_64-darwin-20/2.7.0/mysql2-0.5.3/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/ry/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/mysql2-0.5.3 for inspection.
Results logged to /Users/ry/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/extensions/x86_64-darwin-20/2.7.0/mysql2-0.5.3/gem_make.out

An error occurred while installing mysql2 (0.5.3), and Bundler cannot continue.
Make sure that `gem install mysql2 -v '0.5.3' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  mysql2
```
以下を実施。

```
brew install mysql
```

その他、以下も実施。

```
$ bundle config --local build.mysql2 "--with-cppflags=-I/usr/local/opt/openssl/include"
$ bundle config --local build.mysql2 "--with-ldflags=-L/usr/local/opt/openssl/lib"
$ export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/opt/openssl/lib/
```

**Comment by ryojsb** [comment]
```
$ bundle install
...
An error occurred while installing puma (4.3.5), and Bundler cannot continue.
Make sure that `gem install puma -v '4.3.5' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  puma
```

以下を実施

```
gem install puma:4.3.5 -- --with-cflags="-Wno-error=implicit-function-declaration"
```
